apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account
  namespace: motegao-prod
type: Opaque
data:
  # Base64 encoded content of gcp-motegao-service-account.json
  # To create this, run:
  # kubectl create secret generic gcp-service-account \
  #   --from-file=gcp-motegao-service-account.json=./gcp-motegao-service-account.json \
  #   --namespace=motegao-prod --dry-run=client -o yaml > k8s/gcp-credentials-secret.yaml
  gcp-motegao-service-account.json: ""
