apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: motegao-prod

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - persistent-volumes.yaml
  - mongodb-deployment.yaml
  - redis-deployment.yaml
  - rabbitmq-deployment.yaml
  - api-deployment.yaml
  - app-deployment.yaml
  - worker-deployment.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
