apiVersion: v1
kind: Secret
metadata:
  name: motegao-secrets
  namespace: motegao-prod
type: Opaque
stringData:
  MONGO_ROOT_PASSWORD: "changeme" # Replace with actual password
  SECRET_KEY: "changeme" # Replace with actual secret key
  NEXT_PUBLIC_API_URL: "http://localhost/api"
