name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.GCP_USERNAME }}/projects/motegao
            git pull origin main
            git checkout main
            docker compose --env-file .env.production -f docker-compose.ssl.yml up -d --build mongodb redis api app nginx certbot

  deploy-workers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker_ip: ["10.148.0.5", "10.148.0.6", "10.148.0.7", "10.148.0.8"]
      fail-fast: false
      max-parallel: 10

    steps:
      - name: Deploy Worker ${{ matrix.worker_ip }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ssh -o StrictHostKeyChecking=no dev@${{ matrix.worker_ip }} << 'ENDSSH'
              ./deploy-worker.sh up -d --build
            ENDSSH
